exp_name: independent_concept
seed: 42
device: cuda:1

DATA:
  dataset_name: dsprites
  data_dir: /home/lorenzo/generative-cem/data/dsprites/interim/full
  file_name: dsprites_leakage
  file_type: npz
  n_channels: 1
  img_size: 64
  n_classes: 2
  n_concepts: 3
  n_embed_concepts: 16
  n_model_concepts: 3
  selected_concepts: [1,3,5]

REPORTS:
  models_dir: ./models/
  logs_dir: ./logs/
  reports_dir: ./reports/

MODEL:
  freeze_encoder: False
  # No need for independent concept a pre-trained model as it is an indipendenet concept model
  # pretrained_model_path: ./models/dsprites_partial/oracle/model_best.pt

TRAINING:
  num_epochs: 60
  batch_size: 128
  learning_rate: 0.0001
  warmup_epochs: 5
  early_stopping: 10

  weight_concept_loss: 1.0
  weight_task_loss: 0.0
  weight_rec_loss: 0.0
  weight_lat_loss:  0.0
  weight_orth_loss: 0.0