exp_name: independent_concept
seed: 42
device: cuda:0

DATA:
  dataset_name: camelyon
  data_dir: /home/riccardo/Github/generative-cem/data/camelyon/interim/cmeasures 
  n_channels: 3
  img_size: 224
  n_classes: 2
  n_concepts: 6
  n_embed_concepts: 16
  n_model_concepts: 0
  # selected_concepts: [0,1,3]  # Lower std -> higher variability -> probably more discrimative
  norm_concepts: True

REPORTS:
  models_dir: ./models/
  logs_dir: ./logs/
  reports_dir: ./reports/

MODEL:
  skip_connection: True
  freeze_encoder: False
  # pretrained_model_path: ./models/camelyon/independent_concept

TRAINING:
  num_epochs: 30
  batch_size: 128
  learning_rate: 0.0005
  warmup_epochs: 5
  early_stopping: 10

  weight_concept_loss: 1.0
  weight_task_loss: 0.0
  weight_rec_loss: 0.0
  weight_lat_loss:  0.0
  weight_orth_loss: 0.0